### ISSUE TITLE
PageModule components rendered using ContentZone re-render when using useRouter

### ISSUE THREAD

**Issue by jsimondshiebing** [agility/agility-next#21]
I have been trying to build a locator component that is connected to Agility as a page module and rendered using the ContentZone on a page for placement. There are currently no fields configured on the page module and it is only really being used for placement on the page with plans to connect copy fields in the future. The locator has a search form that onSubmit sets component state and then updates the query string with that value however using the useRouter hook and router.push with shallow routing is still causing the component to completely re-render and lose it's state causing the content to flash as it is being reset. I have narrowed this down to being caused by the RenderModules component that wraps all the page module components as rendering the locator on its own outside the ContentZone does not cause re-renders and behaves normally with the useRouter hook and shallow routing.

**Comment by joelvarty** [comment]
Are you able to share your code with us to help debug this?

**Comment by jsimondshiebing** [comment]
hi @joelvarty thanks for taking a look, unfortunately i can't share exact code as it's source is in a private repo however i have a demo component that i've written here that uses the same overall functions and has the same re-rendering issue. below we have our default Agility template that renders the ContentZone component from the @agility/nextjs package and accepts the getModule function:
```js
import React from 'react'
import { ContentZone } from '@agility/nextjs'
import { getModule } from '../../agility-pageModules'

const DefaultTemplate = (props:any) => {
  return (
    <>
      <ContentZone name='Content' {...props} getModule={getModule}  />
    </>
  )
}

export default DefaultTemplate
```
our getModule function then maps the module name to the corresponding component:
```js
import { ModuleWithInit, Module } from '@agility/nextjs'
import Demo from './Demo'

const allModules = [
  {
    name: 'Demo', module: Demo
  },
]

export const getModule = (moduleName: string): ModuleWithInit | null => {
  if (!moduleName) return null
  const obj = allModules.find(
    (m) => m.name.toLowerCase() === moduleName.toLowerCase()
  )

  return obj.module as ModuleWithInit<object>
}
```
then below is the Demo component where we have a form with an onSubmit handler that updates the querystring:
```js
import { useState } from 'react'
import { useRouter } from 'next/router'

const Demo = () => {
  const router = useRouter()
  const { query } = router
  const [keyword, setKeyword] = useState(query?.keyword || '')
  const [errors, setErrors] = useState({
    keywordError: ''
  })
  const updateRoute = ({ keyword }) => {
    router.push({
      pathname: router.asPath.split('?')[0],
      query   : {
        ...(keyword ? {
          keyword
        } : {
        })
      }
    }, undefined, {
      shallow: true
    })
  }

  const handleSubmit = (event) => {
    event.preventDefault()
    if (keyword) {
      setErrors({
        ...errors,
        keywordError: ''
      })
      updateRoute({
        keyword: keyword
      })
    } else {
      setErrors({
        ...errors,
        keywordError: 'Please enter a valid search.'
      })
    }
  }

  const handleKeywordChange = (event) => {
    setKeyword(event.target.value)
    if (errors?.keywordError) {
      setErrors({
        ...errors,
        keywordError: ''
      })
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor='keyword'>
        <span>Search:</span>
        <input
          id='keyword'
          aria-describedby='keyword-error'
          onChange={handleKeywordChange}
        />
        <span id='keyword-error'>{errors?.keywordError || ''}</span>
      </label>
    </form>
  )
}

export default Demo
```
if you are using React devtools and try monitoring the component you'll see the component state update and then it clears as the component re-renders. from what i can tell this is happening on the RenderModules component that is triggering the various page module components to re-render.

**Comment by joelvarty** [comment]
Hi there - I think this is a next.js behaviour that we can't easily change - https://github.com/vercel/next.js/discussions/18072 

A workaround is to use the base `window.history` api like this:

```
const updateRoute = ({ keyword }: { keyword: any }) => {
		
	const newUrl = `${router.asPath.split("?")[0]}?keyword=${ encodeURIComponent( keyword)}`
	window.history.replaceState({...window.history.state, as: newUrl, url: newUrl}, "", newUrl)
		
}
```

**Comment by jsimondshiebing** [comment]
the thing that i'm struggling with is i am not seeing this behavior when using the same component outside of the ContentZone, for example if i were to render the Demo component as a sibling of ContentZone the query string updates as you'd expect and the component doesn't unmount and remount. if we add a useEffect to the Demo component like this
```js
useEffect(() => {
    console.log('mount')

    return () => console.log('unmount')
  }, [])
```
we can see when the component has mounted and when it has unmounted, leaving Demo inside of the ContentZone and rendering with getModule causes the component to unmount and mount from what i can see twice, however if we remove ContentZone from DefaultTemplate and render Demo on its own like this:
```js
import React from 'react'
import { ContentZone } from '@agility/nextjs'
import Demo from './Demo

const DefaultTemplate = (props:any) => {
  return (
    <>
      <Demo  />
    </>
  )
}

export default DefaultTemplate
```
it doesn't unmount and remount after submitting the form.

as for the global data for passing in from getStaticProps i was actually hoping for a way to pass down a component's client-side props down into sub-components. for example we need pull a user's geolocation using navigator.geolocation.getCurrentPosition and pass that into the SiteHeader as well as a sub-component. since navigator is only accessible through the browser we can't use getStaticProps to pull that and rather than making that request twice ideally we would pull that info in a useEffect in the Layout and then pass that down into both SiteHeader and the sub-component that needs it.

**Comment by jsimondshiebing** [comment]
hey @joelvarty following up here as i had some time to further investigate. i cloned the agility-next repo locally and tried updating the ContentZone component to see if i could find what the cause of the re-renders was. in the end i think there's an issue with the ContentZone referencing an internal component of RenderModules that is causing the behavior. to verify this i updated the ContentZone to strip out RenderModules like so:

```js
import React, { FC } from 'react';
import { ContentZoneProps } from './types';


export const ContentZone:FC<ContentZoneProps> = ({ name, page, sitemapNode, dynamicPageItem, languageCode, channelName, getModule, isDevelopmentMode, isPreview, globalData }) => {
	if (!page) return null

	const modules = page.zones[name]
	
	return (
		<>
			{modules.map(m => {
				const AgilityModule = getModule(m.moduleName)

				let props = {
					page,
					sitemapNode,
					dynamicPageItem,
					module: m.item,
					languageCode,
					channelName,
					customData: m.customData || null,
					isDevelopmentMode,
					isPreview,
					globalData: globalData
 
			 }

			 if (AgilityModule) {
					return <AgilityModule  key={m.item.contentID} { ... props} />
				} else {
					throw new Error(`React Component for ${m.moduleName} was not found in the Agility Modules list.`)
				}
			})}
		</>
	)
}
```
this does the exact same thing it currently does but without the RenderModules component acting as a middleman between the ContentZone wrapper and the pageModules we render within it. i then simply updated my project's package.json to install @agility/nextjs from my local machine rather than the npm registry and i am now no longer seeing the issues.

wondering if you could verify on your end a couple things: one being what the original RenderModules component nested with ContentZone was doing and if there are any potential repercussions for removing it and letting ContentZone do the logic. second i'd like to get confirmation that you are seeing this behavior on your end and or if there is something else that needs to be investigated.

**Comment by joelvarty** [comment]
We have a PR in for this - should be ready to roll by tomorrow!

**Comment by jsimondshiebing** [comment]
thanks for helping look into this @joelvarty!
